"""
Skill Matching — Interview Intelligence.

An adaptive, template-driven interview question generator (intelligence
design §9), deliberately template-driven rather than AI-generated per the
algorithm design's own hackathon-scope simplification (§12): this keeps
grounding trivial and output predictable for a live demo, and — matching
the roadmap's dependency note — needs only Milestone 8's deterministic
output, nothing from the AI reasoning layer (Milestone 9).

Every question is generated by directly targeting a structure already
computed, never by asking anything to freely invent interview questions:

- Gap-verification — probes CRITICAL/MODERATE gaps with NO mitigating
  evidence at all (match_type NONE). Resumes are lossy; the candidate may
  have relevant experience the structured data never captured.
- Transferability-verification — probes CRITICAL/MODERATE gaps that DO
  have transferable/adjacent evidence (e.g. PyTorch experience against a
  TensorFlow requirement), testing whether the claimed transfer actually
  holds in practice or is superficial.
- Evidence-depth-verification — probes EXACT matches whose underlying
  evidence is weak (a bare mention, no real depth signal), checking
  whether the claimed skill has real depth behind it.

Only CRITICAL and MODERATE gaps generate questions — LOW_IMPACT and
NICE_TO_HAVE gaps are, by gap_analysis.py's own design, gaps that don't
meaningfully change the hire/no-hire calculus, so spending scarce
interview time probing them wouldn't answer a real recruiter problem.

Difficulty scales with the underlying evidence's skill_confidence
(reusing confidence.py's skill_confidence — the same signal already
computed, not a re-derived one): strong-but-unverified evidence earns a
harder, more specific PROBING question; weak or absent evidence starts
with a FOUNDATIONAL one.

SCOPE BOUNDARY, deliberately enforced by this file's public surface: this
is decision-support ONLY. It suggests questions for a human recruiter to
ask; it never receives, scores, or evaluates a candidate's answer. Adding
any such capability would be a materially different, higher-stakes system
(automated candidate evaluation) that is explicitly out of scope for this
module per the intelligence design.
"""

from datetime import date
from enum import Enum

from pydantic import BaseModel

from ..confidence import skill_confidence
from ..constants import INTERVIEW_EVIDENCE_QUESTION_THRESHOLD, INTERVIEW_STRONG_EVIDENCE_THRESHOLD
from ..gap_analysis import Gap, GapSeverity
from ..matching import MatchType, SkillMatch


class QuestionPurpose(str, Enum):
    GAP_VERIFICATION = "gap_verification"
    EVIDENCE_DEPTH_VERIFICATION = "evidence_depth_verification"
    TRANSFERABILITY_VERIFICATION = "transferability_verification"


class QuestionDifficulty(str, Enum):
    FOUNDATIONAL = "foundational"
    PROBING = "probing"


class InterviewQuestion(BaseModel):
    """One suggested question, tagged with why it's being asked."""

    question: str
    purpose: QuestionPurpose
    difficulty: QuestionDifficulty
    related_skill: str


_GAP_PRIORITY_SEVERITIES = frozenset({GapSeverity.CRITICAL, GapSeverity.MODERATE})


def _gap_verification_question(skill: str) -> InterviewQuestion:
    return InterviewQuestion(
        question=(
            f"Your background doesn't show direct evidence of {skill}. Have you worked with it "
            "in any capacity — even informally, through coursework, or as part of a broader "
            "project — that might not have come through in your resume?"
        ),
        purpose=QuestionPurpose.GAP_VERIFICATION,
        difficulty=QuestionDifficulty.FOUNDATIONAL,
        related_skill=skill,
    )


def _transferability_verification_question(
    required_skill: str, related_skill: str, related_confidence: float
) -> InterviewQuestion:
    if related_confidence >= INTERVIEW_STRONG_EVIDENCE_THRESHOLD:
        return InterviewQuestion(
            question=(
                f"Your background shows solid experience with {related_skill}, which is closely "
                f"related to {required_skill}. Walk me through specifically how you'd apply that "
                f"experience to a {required_skill} task, and where you'd expect the biggest "
                "differences to be."
            ),
            purpose=QuestionPurpose.TRANSFERABILITY_VERIFICATION,
            difficulty=QuestionDifficulty.PROBING,
            related_skill=required_skill,
        )

    return InterviewQuestion(
        question=(
            f"You have some exposure to {related_skill}, which is related to {required_skill}. "
            f"Have you had any direct exposure to {required_skill} itself, even briefly?"
        ),
        purpose=QuestionPurpose.TRANSFERABILITY_VERIFICATION,
        difficulty=QuestionDifficulty.FOUNDATIONAL,
        related_skill=required_skill,
    )


def _evidence_depth_question(skill: str, confidence: float) -> InterviewQuestion:
    if confidence >= INTERVIEW_STRONG_EVIDENCE_THRESHOLD:
        return InterviewQuestion(
            question=(
                f"Your background mentions {skill} without much supporting detail. Can you walk "
                f"through a specific, technically detailed example of a time you used {skill} in "
                "production?"
            ),
            purpose=QuestionPurpose.EVIDENCE_DEPTH_VERIFICATION,
            difficulty=QuestionDifficulty.PROBING,
            related_skill=skill,
        )

    return InterviewQuestion(
        question=(
            f"Can you tell me more about your experience with {skill}? What's a project or task "
            "where you actually applied it?"
        ),
        purpose=QuestionPurpose.EVIDENCE_DEPTH_VERIFICATION,
        difficulty=QuestionDifficulty.FOUNDATIONAL,
        related_skill=skill,
    )


def generate_interview_questions(
    matches: list[SkillMatch], gaps: list[Gap], as_of: date
) -> list[InterviewQuestion]:
    """
    Generate a decision-support question set for a recruiter, grounded
    entirely in already-computed matches and gaps. Never scores or
    evaluates a candidate's answer — see module docstring.
    """
    questions: list[InterviewQuestion] = []

    for gap in gaps:
        if gap.severity not in _GAP_PRIORITY_SEVERITIES:
            continue

        if gap.match_type in (MatchType.TRANSFERABLE, MatchType.ADJACENT) and gap.matched_via:
            related_skill = gap.matched_via[0].raw_text
            related_confidence = skill_confidence(gap.matched_via, as_of)
            questions.append(
                _transferability_verification_question(
                    gap.requirement.raw_text, related_skill, related_confidence
                )
            )
        else:
            questions.append(_gap_verification_question(gap.requirement.raw_text))

    for match in matches:
        if match.match_type != MatchType.EXACT:
            continue
        confidence = skill_confidence(match.matched_candidate_skills, as_of)
        if confidence < INTERVIEW_EVIDENCE_QUESTION_THRESHOLD:
            questions.append(_evidence_depth_question(match.requirement.raw_text, confidence))

    return questions
